package airtrafficcontrol;

import java.util.Arrays;
import java.util.stream.IntStream;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hashan
 */
public class FindRoutesUI extends javax.swing.JFrame {
    AirTrafficControl mainData;
    /**
     * Creates new form FindRoutesUI
     */
    public FindRoutesUI() {
        initComponents();
    }
    
    public FindRoutesUI(AirTrafficControl atc) {
        initComponents();
        mainData = atc;
        onLoad();
    }
    
    final void onLoad() {
        cmbAirports.removeAllItems();
        cmbAirports.setToolTipText(("Select Airports"));
        for(int i=0;i<mainData.codes.length; i++) {
            cmbAirports.addItem(new ComboItem(mainData.codes[i]+" - "+mainData.airports[0][i],mainData.codes[i]));
        }
        tblAdded.setModel(new DefaultTableModel(new Object[]{"Airport Code", "Airport Name"},0));
        tblRoutes.setModel(new DefaultTableModel(new Object[]{"Airport Code", "Shortest Route"},0));
    }
    
    public void removeRows(int[] indices) {
        DefaultTableModel model = (DefaultTableModel) tblAdded.getModel();
        Arrays.sort(indices);
        for (int i = indices.length - 1; i >= 0; i--) {
            model.removeRow(indices[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoutes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdded = new javax.swing.JTable();
        cmbAirports = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIND ROUTES");
        setPreferredSize(new java.awt.Dimension(1115, 621));
        setResizable(false);
        getContentPane().setLayout(null);

        tblRoutes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblRoutes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 200, 530, 400);

        tblAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 2", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAdded);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 530, 400);

        cmbAirports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAirportsActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAirports);
        cmbAirports.setBounds(50, 70, 330, 30);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Selected Airports");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 120, 200, 30);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton1.setText("Find Route");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 50, 200, 60);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Shortest Route and Duration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 140, 360, 40);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Select Airport:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 30, 170, 30);

        btnAdd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(390, 70, 140, 30);

        btnDelete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(230, 570, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int count = tblAdded.getRowCount();
        String[] codes = new String[count];
        DefaultTableModel model = (DefaultTableModel) tblAdded.getModel();
        for(int i=0;i<count;i++)
        {
            String acode = model.getValueAt(i, 0).toString();
            codes[i]=acode;
        }
        mainData.getSelectedAirports(codes);
        mainData.MASSolve();
        mainData.printPaths(model, mainData.MASSolution, 0);
        model = (DefaultTableModel) tblRoutes.getModel();
        for(int i=0;i<count-1;i++)
        {
            
           double x = mainData.MASSolution[0][i];
           
           
           int y = (int)x;
           int v = (int)mainData.MASSolution[1][i];
           model.addRow(new Object[]{mainData.MAScodes[y].toString(),mainData.MAScodes[v].toString()});
           
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String airportCode = ((ComboItem)(cmbAirports.getSelectedItem())).getValue();
        String airportName = ((ComboItem)(cmbAirports.getSelectedItem())).getKey();
        DefaultTableModel model = (DefaultTableModel) tblAdded.getModel();
        
        boolean isExist = false;
        
        for (int count = 0; count < model.getRowCount(); count++){
           String acode = model.getValueAt(count, 0).toString();
           if(airportCode.equals(acode)){
               isExist = true;
           }
        }
        
        if(!isExist){
            model.addRow(new Object[]{airportCode, airportName});
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbAirportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAirportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAirportsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = tblAdded.getSelectedRows();
        removeRows(selectedRows);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindRoutesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindRoutesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindRoutesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindRoutesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindRoutesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox cmbAirports;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAdded;
    private javax.swing.JTable tblRoutes;
    // End of variables declaration//GEN-END:variables
}
