/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airtrafficcontrol;

/**
 *
 * @author TMJ
 */
public class MainMenu extends javax.swing.JPanel {
    AirTrafficControl maindata;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    public MainMenu(AirTrafficControl Main) {
        initComponents();
        maindata = Main;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAirport = new javax.swing.JButton();
        btnUpdateAirport = new javax.swing.JButton();
        btnDeleteAirport = new javax.swing.JButton();
        btnFindShortestPath = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btnAddAirport.setText("Add Airport");
        btnAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirportActionPerformed(evt);
            }
        });

        btnUpdateAirport.setText("Update Airport");
        btnUpdateAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirportActionPerformed(evt);
            }
        });

        btnDeleteAirport.setText("Delete Airport");
        btnDeleteAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirportActionPerformed(evt);
            }
        });

        btnFindShortestPath.setText("Find Shortest Path");
        btnFindShortestPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindShortestPathActionPerformed(evt);
            }
        });

        jButton1.setText("Find Shourtest Route");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFindShortestPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnAddAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUpdateAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDeleteAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnFindShortestPath, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FindRoutesUI uia = new FindRoutesUI(maindata);
        uia.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAirportActionPerformed

    private void btnDeleteAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAirportActionPerformed

    private void btnFindShortestPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindShortestPathActionPerformed
        // TODO add your handling code here:
        FindRouteUI uia = new FindRouteUI(maindata);
        uia.setVisible(true);
    }//GEN-LAST:event_btnFindShortestPathActionPerformed

    private void btnUpdateAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateAirportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirport;
    private javax.swing.JButton btnDeleteAirport;
    private javax.swing.JButton btnFindShortestPath;
    private javax.swing.JButton btnUpdateAirport;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
