/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airtrafficcontrol;

/**
 *
 * @author hashan
 */
public class MainAppUI extends javax.swing.JFrame {
    AirTrafficControl mainData;
    /**
     * Creates new form MainAppUI
     */
    public MainAppUI() {
        initComponents();
    }
    
    public MainAppUI(AirTrafficControl atc) {
        initComponents();
        mainData = atc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAirport = new javax.swing.JButton();
        btnUpdateAirport = new javax.swing.JButton();
        btnDeleteAirport = new javax.swing.JButton();
        btnFindShortestPath = new javax.swing.JButton();
        btnAllRoutes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air Traffic Control System");
        setMaximumSize(new java.awt.Dimension(886, 563));
        setMinimumSize(new java.awt.Dimension(886, 563));
        setPreferredSize(new java.awt.Dimension(886, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAirport.setText("Add Airport");
        btnAddAirport.setFocusPainted(false);
        btnAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirportActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 70));

        btnUpdateAirport.setText("Update Airport");
        btnUpdateAirport.setFocusPainted(false);
        btnUpdateAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirportActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 210, 70));

        btnDeleteAirport.setText("Delete Airport");
        btnDeleteAirport.setFocusPainted(false);
        btnDeleteAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirportActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 200, 70));

        btnFindShortestPath.setText("Find Shortest Path");
        btnFindShortestPath.setFocusPainted(false);
        btnFindShortestPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindShortestPathActionPerformed(evt);
            }
        });
        getContentPane().add(btnFindShortestPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 230, 90));

        btnAllRoutes.setText("Find All Routes");
        btnAllRoutes.setFocusPainted(false);
        btnAllRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllRoutesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAllRoutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 220, 90));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("Air Traffic Control System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 610, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirportActionPerformed
        // TODO add your handling code here:
        AddAirportUI uia = new AddAirportUI(mainData);
        uia.setDefaultCloseOperation(AddAirportUI.DISPOSE_ON_CLOSE);
        uia.setResizable(false);
        uia.setLocationRelativeTo(null);
        uia.setVisible(true);
    }//GEN-LAST:event_btnAddAirportActionPerformed

    private void btnUpdateAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirportActionPerformed
        // TODO add your handling code here:
        UpdateAirportUI uiu = new UpdateAirportUI(mainData);
        uiu.setDefaultCloseOperation(UpdateAirportUI.DISPOSE_ON_CLOSE);
        uiu.setResizable(false);
        uiu.setLocationRelativeTo(null);
        uiu.setVisible(true);
    }//GEN-LAST:event_btnUpdateAirportActionPerformed

    private void btnDeleteAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirportActionPerformed
        // TODO add your handling code here:
        DeleteAirportUI uid = new DeleteAirportUI(mainData);
        uid.setDefaultCloseOperation(DeleteAirportUI.DISPOSE_ON_CLOSE);
        uid.setResizable(false);
        uid.setLocationRelativeTo(null);
        uid.setVisible(true);
    }//GEN-LAST:event_btnDeleteAirportActionPerformed

    private void btnFindShortestPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindShortestPathActionPerformed
        // TODO add your handling code here:
        FindRouteUI uifr = new FindRouteUI(mainData);
        uifr.setDefaultCloseOperation(FindRouteUI.DISPOSE_ON_CLOSE);
        uifr.setResizable(false);
        uifr.setLocationRelativeTo(null);
        uifr.setVisible(true);
    }//GEN-LAST:event_btnFindShortestPathActionPerformed

    private void btnAllRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllRoutesActionPerformed
        // TODO add your handling code here:
        FindRoutesUI uia = new FindRoutesUI(mainData);
        uia.setDefaultCloseOperation(FindRoutesUI.DISPOSE_ON_CLOSE);
        uia.setResizable(false);
        uia.setLocationRelativeTo(null);
        uia.setVisible(true);
    }//GEN-LAST:event_btnAllRoutesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirport;
    private javax.swing.JButton btnAllRoutes;
    private javax.swing.JButton btnDeleteAirport;
    private javax.swing.JButton btnFindShortestPath;
    private javax.swing.JButton btnUpdateAirport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
